### ISSUE TITLE
Close/Free for Performance?

### ISSUE THREAD

**Issue by ezetojo** [daveismyname/pdo-wrapper#1]
Hello david. I loved the code.
First of all, it's worth clarifying that I'm a newbie in PHP.
I have tried some times to use PHP in previous projects (in shared hostings) and they have caught my attention because the scripts consumed a lot of memory, I remember that something I did to solve it was to close the queries and connections.
You do not need any of that in this wrapper?
I would appreciate it if you could clarify it to me.
Greetings.

**Comment by daveismyname** [comment]
Hi Ezetojo, thanks!

PDO closes the connection automatically at the end of the script so it shouldn't need manually closing, that is why I never put a closing part into the wrapper.

This is only a wrapper for PDO so if a lot of memory is being used it could be due to a complex query being executed.

You can add index to your database to make querying faster and also optimise your query by only selecting what you need. That should help use less memory.

**Comment by ezetojo** [comment]
Wow, thanks for the speed of response David!
Excellent, I suppose then that the previous times I was using mysqli.
